config/routes.rb
Deductapp::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :transactions, :only => [:index, :show, :create]
      resources :budgets, :only => [:index, :show]
    end
  end

  resources :budgets

  resources :transactions 

  resources :favourites

  devise_for :users
  resources :users

  get "week/:year/:month/:day" => "home#week", :as => :week_of
  
  authenticated do
    root :to => 'home#index'
  end
  
  root :to => 'home#guest'

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  attr_accessible :amount, :name, :budget_type
  
 	validates :name, :presence => true
  validates :budget_type, :presence => true
  validates :amount, :presence => true
  
	validates :amount, :numericality => true

  has_many :transactions
  has_and_belongs_to_many :users
  has_many :favourites

  public 
    
  def icon
    if budget_type == 'spending'
      'shopping-cart'
    else
      'bar-chart'
    end
  end

  def current_amount(year, month, day)
    @week_start = Time.new(year, month, day, 0, 0, 0, 0)
    @week_end = @week_start + 1.week

    if budget_type == 'spending'
      amount_for_week_left = amount
      transactions.where('created_at between ? and ?', @week_start, @week_end).order("created_at DESC").each do |transaction|
        if transaction.transaction_type == 1
          amount_for_week_left = amount_for_week_left - transaction.amount
        else
          amount_for_week_left = amount_for_week_left + transaction.amount
        end
      end
      amount_for_week_left
    else
      20
    end
  end
end

app/controllers/api/v1/budgets_controller.rb
class Api::V1::BudgetsController < ApiController
  respond_to :json
  before_filter :check_file
  before_filter :check_token
  before_filter :verify_authenticity_token
  
  def index
    limit = params[:limit] || 10
    offset = params[:offset] || 0
    
    _budgets = current_user.budgets.limit(limit).offset(offset)
    
    budgets = Hash['budgets' => _budgets]
    render :status=>200, :json=>budgets
  end

  def show
    limit = params[:limit] || 10
    offset = params[:offset] || 0

    _budget = current_user.budgets.find(params[:id])
    _transactions = _budget.transactions.order('created_at DESC').limit(limit).offset(offset).select("id, name, amount, description, transaction_type")
    
    budget = Hash['id' => _budget.id, 'name' => _budget.name, 'amount' => _budget.amount, 'budget_type' => _budget.budget_type, 'transactions' => _transactions]
    render :status=>200, :json=>budget
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_time_zone

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = current_user.budgets

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @budgets }
    end
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @budget = Budget.find(params[:id])
    @transactions = @budget.transactions.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @budget }
    end
  end

  # GET /budgets/new
  # GET /budgets/new.json
  def new
    @budget = Budget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @budget }
    end
  end

  # GET /budgets/1/edit
  def edit
    @budget = Budget.find(params[:id])
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(params[:budget])
    @budget.users << current_user

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render json: @budget, status: :created, location: @budget }
      else
        format.html { render action: "new" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /budgets/1
  # PUT /budgets/1.json
  def update
    @budget = Budget.find(params[:id])

    respond_to do |format|
      if @budget.update_attributes(params[:budget])
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to budgets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= semantic_form_for @budget, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.semantic_errors %>
  
  <%= f.inputs do %>
    <%= f.input :name, :input_html => { :class => "input-xlarge" } %>
    <%= f.input :budget_type, :label => 'Type', :as => :radio, :collection => { "Spending Budget" => 'spending', "Savings Budget" => 'saving' }, :input_html => { :class => "input-xlarge" } %>
    <%= f.input :amount, :input_html => { :class => "input-xlarge" } %>
  <% end %>
  
  <%= f.actions do %>
    <%= f.action :submit, :button_html => { :class => "btn-inverse" } %>
  <% end %>
<% end %>

app/views/budgets/edit.html.erb
<div class="page-header">
	<h1>Editing budget</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Delete', @budget, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<div class="page-header">
	<h1>Your Budgets</h1>
</div>

<ul class="nav nav-tabs nav-stacked">
<% @budgets.each do |budget| %>
  <li>
    <%= link_to budget, :class => "clearfix" do %>
      <span class="pull-left">
        <strong><%= budget.name %></strong> <br />
        $<%= number_with_precision budget.amount, :precision => 2 %>
      </span>
    <% end %>
  </li>
<% end %>
</ul>

app/views/budgets/new.html.erb
<div class="page-header">
	<h1>New budget</h1>
</div>

<%= render 'form' %>

app/views/budgets/show.html.erb
<div class="page-header">
	<h1 class="clearfix"><%= @budget.name %> <small class="pull-right"><%= link_to edit_budget_path(@budget) do %><i class="icon-edit"></i><% end %></small></h1>
</div>

<ul class="nav nav-tabs nav-stacked">
<% @transactions.each do |transaction| %>
  <li>
    <%= link_to transaction, :class => 'clearfix' do %>
      <span class="pull-left">
        <i class="icon-<%= transaction.icon %>"></i>&nbsp;
      </span>
      <span class="pull-left">
        <strong><%= transaction.name %></strong> <br />
        <%= number_to_currency(transaction.amount) %> on <%= transaction.created_at.strftime('%e/%-m/%Y') %>
      </span>
    <% end %>
  </li>
<% end %>
</ul>

<%= will_paginate @transactions, :page_links => false, :previous_label => "<i class=\"icon-chevron-left\"></i>", :next_label => "<i class=\"icon-chevron-right\"></i>" %>