config/routes.rb
Deductapp::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :transactions, :only => [:index, :show, :create]
      resources :budgets, :only => [:index, :show]
    end
  end

  resources :budgets

  resources :transactions 

  resources :favourites

  devise_for :users
  resources :users

  get "week/:year/:month/:day" => "home#week", :as => :week_of
  
  authenticated do
    root :to => 'home#index'
  end
  
  root :to => 'home#guest'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  attr_accessible :amount, :budget_id, :description, :name, :user_id, :tag_list, :transaction_type

  validates :name, :presence => true
  validates :amount, :presence => true
  validates :user_id, :presence => true
  validates :budget_id, :presence => true
  validates :transaction_type, :presence => true

  validates :amount, :numericality => true

  acts_as_taggable
  
  belongs_to :budget
  belongs_to :user

  public

  def icon
    if transaction_type === 1
      'minus'
    else
      'plus'
    end
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_time_zone

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = current_user.favourites

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @favourites }
    end
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/new
  # GET /favourites/new.json
  def new
    @favourite = Favourite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @favourite }
    end
  end

  # GET /favourites/1/edit
  def edit
    @favourite = Favourite.find(params[:id])
  end

  # POST /favourites
  # POST /favourites.json
  def create
    @favourite = Favourite.new(params[:favourite])
    @favourite.user_id = current_user.id

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to @favourite, notice: 'Favourite was successfully created.' }
        format.json { render json: @favourite, status: :created, location: @favourite }
      else
        format.html { render action: "new" }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /favourites/1
  # PUT /favourites/1.json
  def update
    @favourite = Favourite.find(params[:id])

    respond_to do |format|
      if @favourite.update_attributes(params[:favourite])
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to favourites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= semantic_form_for @favourite, :html => { :class => "form-horizontal" } do |f| %>
  <%= f.inputs do %>
    <%= f.input :name, :input_html => { :class => "input-xlarge" } %>
    <%= f.input :transaction_type, :as => :radio, :collection => Hash[:Deduction => 1, :Addition => 2] %>
    <%= f.input :amount, :input_html => { :class => "input-xlarge" } %>
    <%= f.input :description, :input_html => { :class => "input-xlarge", :rows => 3 } %>
    <%= f.input :budget_id, :required => true, :as => :select, :collection => Hash[current_user.budgets.map{|b| [b.name, b.id]}], :input_html => { :class => "input-xlarge", :rows => 3 } %>
    <%= f.input :tag_list, :input_html => { :class => "input-xlarge" } %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/favourites/edit.html.erb
<div class="page-header">
  <h1>Edit favourite</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<div class="page-header">
	<h1>Your Favourites</h1>
</div>

<ul class="nav nav-tabs nav-stacked">
<% @favourites.each do |favourite| %>
  <li>

    <%= link_to favourite, :class => 'clearfix' do %>
      <span class="pull-left">
        <strong><%= favourite.name %></strong> <br />
        <%= number_to_currency(favourite.amount) %>
      </span>
      <span class="pull-right">
        <% if !favourite.budget.nil? %>
          <br /><%= favourite.budget.name %>
        <% end %>
      </span>
    <% end %>
  </li>
<% end %>
</ul>

app/views/favourites/new.html.erb
<div class="page-header">
	<h1>New favourite</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/show.html.erb
<div class="page-header">
  <h1>Your Favourite</h1>
</div>

<p>
  <b>Name:</b>
  <%= @favourite.name %>
</p>

<p>
  <b>Amount:</b>
  <%= @favourite.amount %>
</p>

<p>
  <b>Description:</b>
  <%= @favourite.description %>
</p>

<p>
  <b>Budget:</b>
  <%= @favourite.budget.name %>
</p>

<p>
  <b>Tags:</b>
  <%= @favourite.tag_list %>
</p>


<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>