config/routes.rb
Deductapp::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tokens, :only => [:create, :destroy]
      resources :transactions, :only => [:index, :show, :create]
      resources :budgets, :only => [:index, :show]
    end
  end

  resources :budgets

  resources :transactions 

  resources :favourites

  devise_for :users
  resources :users

  get "week/:year/:month/:day" => "home#week", :as => :week_of
  
  authenticated do
    root :to => 'home#index'
  end
  
  root :to => 'home#guest'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :week]  
  before_filter :set_time_zone

  def index
      @today = DateTime.now
      @today_start = Time.new(@today.year, @today.month, @today.day, 0, 0, 0, 0)

      @week_start = @today_start - Time.now.wday.days
      @week_end = @week_start + 1.week
      
      @budgets = current_user.budgets
      @transactions = current_user.transactions.where('created_at between ? and ?', @week_start, @week_end).order("created_at DESC, budget_id ASC")

      respond_to do |format|
        format.html # home.html.erb
        format.json { render json: @deductions }
      end
  end

  def week 
    @week_start = Time.new(params[:year], params[:month], params[:day], 0, 0, 0, 0)
    @week_start = @week_start - @week_start.wday.days
    @week_end = @week_start + 1.week

    @budgets = current_user.budgets
    @transactions = current_user.transactions.where('created_at between ? and ?', @week_start, @week_end).order("created_at DESC, budget_id ASC")

    respond_to do |format|
      format.html # home.html.erb
      format.json { render json: @deductions }
    end
  end

  def guest

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_tab_content.html.erb
<div class="container hidden-phone">
  <div class="row">
    <div class="span9">
      <div class="page-header clearfix">
        <h2 class="pull-left">
          Transactions
        </h2>
        
        <ul class="nav nav-pills pull-right" style="margin-bottom: 0">
          <li>
            <%= link_to new_transaction_path do %>
              <i class="icon-bookmark icon-white"></i> <span class="hidden-phone">New Transaction</span>
            <% end %>
          </li>
          <li class="dropdown">
            <a class="dropdown-toggle"
               data-toggle="dropdown"
               href="#">
                <i class="icon-star icon-white"></i> <span class="hidden-phone">Favourites</span>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu ">
                <% current_user.favourites.each do |favourite| %>
                  <li>
                  <%= link_to transactions_path( :transaction => { :name => favourite.name, :amount => favourite.amount, :description => favourite.description, :transaction_type => favourite.transaction_type, :budget_id => favourite.budget_id, :tag_list => favourite.tag_list } ), :method => :post, :class => 'clearfix' do %>
                      <span class="pull-left"><i class="icon-<%= favourite.icon %>"></i>&nbsp;</span>
                      <span class="pull-left">
                        <%= favourite.name %><br />
                        <%= number_to_currency(favourite.amount) %> 
                      </span>
                    <% end %>
                  </li>
                <% end %>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Favourites List', favourites_path %>
                </li>
                <li>
                  <%= link_to new_favourite_path do %>
                    <i class="icon-plus"></i> New Favourite
                  <% end %>
                </li>
            </ul>
          </li>
        </ul>
        
      </div>
      
      <ul class="nav nav-tabs nav-stacked">
      <% @transactions.each do |deduction| %>
        <li>
          <%= link_to deduction, :class => 'clearfix' do %>
            <span class="pull-left">
              <i class="icon-<%= deduction.icon %>"></i>&nbsp;
            </span>
            <span class="pull-left">
              <strong><%= deduction.name %></strong> <br />
              <%= number_to_currency(deduction.amount) %> on <%= deduction.created_at.strftime('%e/%-m/%Y') %>
            </span>
            <span class="pull-right">
              <% if !deduction.budget.nil? %>
                <br />
                <i class="icon-<%= deduction.budget.icon %>"></i>
                <%= deduction.budget.name %>
              <% end %>
            </span>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
    <div class="span3">
      <div class="page-header clearfix">
        <h2 class="pull-left">Budgets</h2>
        <ul class="nav nav-pills pull-right" style="margin-bottom: 0">
          <li>
            <%= link_to new_budget_path do %>
              <i class="icon-plus"></i> New Budget
            <% end %>
          </li>
        </ul>
      </div>
      <ul class="nav nav-tabs nav-stacked">
        <% @budgets.each do |budget| %>
          <li>
            <%= link_to budget, :class => 'clearfix' do %>
              <span class="pull-left">
                <i class="icon-<%= budget.icon %>"></i>&nbsp;
              </span>
              <span class="pull-left">
                <strong><%= budget.name %></strong> <br />
                <%= number_to_currency(budget.current_amount(@week_start.year, @week_start.month, @week_start.day)) %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul>      
      
      <div class="page-header">
        <h2>Weeks</h2>
      </div>
      <ul class="nav nav-tabs nav-stacked">
        <li>
          <%= link_to root_path do %>
            This week
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 6, 3) do %>
            6/3/2012 - 9/6/2012
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 5, 27) do %>
            27/5/2012 - 2/6/2012
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 5, 20) do %>
            20/5/2012 - 26/5/2012
          <% end %>
        </li>
    	  <li>
          <%= link_to week_of_path(2012, 5, 13) do %>
            13/5/2012 - 19/5/2012
          <% end %>
        </li>
	      <li>
          <%= link_to week_of_path(2012, 5, 6) do %>
            6/5/2012 - 12/5/2012
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 4, 29) do %>
            29/4/2012 - 5/5/2012
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>





<div class="tabbable visible-phone">
  <ul class="nav nav-tabs">
    <li class="pull-right">
      <%= link_to '#weeks', :"data-toggle" => "tab" do %>
        <i class="icon-calendar"></i> <span class="hidden-phone">Weeks</span>
      <% end %>
    </li>
    <li class="<%= "active " if params[:addition_page].presence %>pull-right">
      <%= link_to '#week-deduction', :"data-toggle" => "tab" do %>
        <i class="icon-bookmark"></i> <span class="hidden-phone">Transactions</span>
      <% end %>
    </li>
    <li class="<%= "active " if params[:deduction_page].nil? && params[:addition_page].nil? %>pull-right">
      <%= link_to '#budgets', :"data-toggle" => "tab" do %>
        <i class="icon-book"></i> <span class="hidden-phone">Budgets</span>
      <% end %>
    </li>
  </ul>

  <div class="tab-content">

    <div class="<%= "active " if params[:deduction_page].nil? && params[:addition_page].nil? %>tab-pane" id="budgets">
      <ul class="nav nav-tabs nav-stacked">
        <% @budgets.each do |budget| %>
          <li>
            <%= link_to budget, :class => 'clearfix' do %>
              <span class="pull-left">
                <i class="icon-<%= budget.icon %>"></i>&nbsp;
              </span>
              <span class="pull-left">
                <strong><%= budget.name %></strong> <br />
                <%= number_to_currency(budget.current_amount(@week_start.year, @week_start.month, @week_start.day)) %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="<%= "active " if params[:deduction_page].presence %>tab-pane" id="week-deduction">
      <ul class="nav nav-tabs nav-stacked">
      <% @transactions.each do |deduction| %>
        <li>
          <%= link_to deduction, :class => 'clearfix' do %>
            <span class="pull-left">
              <i class="icon-<%= deduction.icon %>"></i>&nbsp;
            </span>
            <span class="pull-left">
              <strong><%= deduction.name %></strong> <br />
              <%= number_to_currency(deduction.amount) %> on <%= deduction.created_at.strftime('%e/%-m/%Y') %>
            </span>
            <span class="pull-right">
              <% if !deduction.budget.nil? %>
                <br />
                <i class="icon-<%= deduction.budget.icon %>"></i>
                <%= deduction.budget.name %>
              <% end %>
            </span>
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>

    <div class="tab-pane" id="weeks">
      <ul class="nav nav-tabs nav-stacked">
        <li>
          <%= link_to week_of_path(2012, 5, 27) do %>
            27/5/2012 - 2/6/2012
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 5, 20) do %>
            20/5/2012 - 26/5/2012
          <% end %>
        </li>
    	  <li>
          <%= link_to week_of_path(2012, 5, 13) do %>
            13/5/2012 - 19/5/2012
          <% end %>
        </li>
	      <li>
          <%= link_to week_of_path(2012, 5, 6) do %>
            6/5/2012 - 12/5/2012
          <% end %>
        </li>
        <li>
          <%= link_to week_of_path(2012, 4, 29) do %>
            29/4/2012 - 5/5/2012
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/home/guest.html.erb
<div class="row">
  <div class="span4">
  	<h3>Watch where your money goes</h3>
  	<p>Monitor where you are spending your money, whether it be lose change or through your banking card. Just enter in the deduction whilst matching it to a budget and your set.</p>
  </div>
  <div class="span4">
  	<h3>Saving for something big</h3>
  	<p>Keep track of what your are saving for. When you know you have enough, go buy it!</p>
  </div>
  <div class="span4">
  	<h3>Graphs are cool again <small>Coming soon</small></h3>
  	<p>We plan on bringing you the sexiest graphs detailing where your deductions and additions are going based on what you are telling us.</p>
  </div>
</div>

app/views/home/home_guest.html.erb
<div class="row">
  <div class="span4">
  	<h3>Watch where your money goes</h3>
  	<p>Monitor where you are spending your money, whether it be lose change or through your banking card. Just enter in the deduction whilst matching it to a budget and your set.</p>
  </div>
  <div class="span4">
  	<h3>Saving for something big</h3>
  	<p>Keep track of what your are saving for. When you know you have enough, go buy it!</p>
  </div>
  <div class="span4">
  	<h3>Graphs are cool again <small>Coming soon</small></h3>
  	<p>We plan on bringing you the sexiest graphs detailing where your deductions and additions are going based on what you are telling us.</p>
  </div>
</div>

app/views/home/index.html.erb
<div class="page-header">
  <h1>This week</h1>
</div>

<%= render 'tab_content' %>

app/views/home/week.html.erb
<div class="page-header">
  <h1>
    Week 
    <small class="pull-right visible-phone" style="margin-top: 8px"><%= @week_start.strftime('%e/%-m/%Y') %> - <%= @week_end.strftime('%e/%-m/%Y') %></small>
    <small class="hidden-phone"><%= @week_start.strftime('%e/%-m/%Y') %> - <%= (@week_end - 1.day).strftime('%e/%-m/%Y') %></small>
  </h1>
</div>

<%= render 'tab_content' %>